openapi: 3.0.1
info:
  title: Book Library
  description: This is a sample booklibrary server.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/example'
tags:
  - name: Book Library Resources
    description: manage books
  - name: Book Management
paths:
  /library/book:
    post:
      tags:
        - Book Management
      operationId: putBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
        required: false
      responses:
        '200':
          description: Post a book instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Invalid book supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookError'
        '406':
          description: Do not set bookid on creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookError'
      x-codegen-request-body-name: body
  '/library/book/{id}':
    get:
      tags:
        - Book Management
      operationId: getBook
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Get a book instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Invalid book id supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookError'
        '404':
          description: Book not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookError'
  /library/books:
    get:
      tags:
        - Book Management
      operationId: getBooks
      responses:
        '200':
          description: Get a book instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookList'
        '400':
          description: Invalid book id supplied
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    BookList:
      type: object
      properties:
        count:
          type: integer
          format: int32
        books:
          type: array
          items:
            $ref: '#/components/schemas/Book'
    Book:
      type: object
      properties:
        title:
          type: string
        publisher:
          type: string
        author:
          type: string
        published:
          type: integer
          format: int32
        bookId:
          type: string
    BookError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
