jetty:
  context: /example
  connectors:
    - port: 8080


jdbc:
  default:
      jdbcUrl: "jdbc:postgresql://localhost:5432/BookDB"
      driverClassName: org.postgresql.Driver
      maximumPoolSize: 1
      username: bookmanager	
      password: password