package com.hmg.demo.app.booklibrary.model.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _BookP was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BookP extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> AUTHOR = Property.create("author", String.class);
    public static final Property<String> BOOK_ID = Property.create("bookId", String.class);
    public static final Property<Integer> PUBLISHED = Property.create("published", Integer.class);
    public static final Property<String> PUBLISHER = Property.create("publisher", String.class);
    public static final Property<String> TITLE = Property.create("title", String.class);

    public void setAuthor(String author) {
        writeProperty("author", author);
    }
    public String getAuthor() {
        return (String)readProperty("author");
    }

    public void setBookId(String bookId) {
        writeProperty("bookId", bookId);
    }
    public String getBookId() {
        return (String)readProperty("bookId");
    }

    public void setPublished(int published) {
        writeProperty("published", published);
    }
    public int getPublished() {
        Object value = readProperty("published");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPublisher(String publisher) {
        writeProperty("publisher", publisher);
    }
    public String getPublisher() {
        return (String)readProperty("publisher");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

}
